version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: bharatflow_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ${POSTGRES_DB:-bharatflow}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Redis for caching and queues (optional for now, but good to have)
  redis:
    image: redis:7
    container_name: bharatflow_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  mongo:
    image: mongo:latest
    container_name: bharatflow_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  redisdata:
  mongodata:
