import { useState, useEffect } from "react";
import { ArrowLeft, Plus, Trash2, Save, Loader2, Search } from "lucide-react";
import { toast } from "sonner";
import { Button } from "../ui/button";
import { Input } from "../ui/input";
import { Label } from "../ui/label";
import { Textarea } from "../ui/textarea";
import { AdaptiveTable } from "../ui/AdaptiveTable";
import { ResponsiveGrid } from "../layout/ResponsiveGrid";
import { useCustomers } from "../../hooks/useParties";
import { useProducts } from "../../hooks/useInventory";
import { useCreateQuotation, useUpdateQuotation } from "../../hooks/useSales";
import type { Quotation, QuotationItem, Party, Product } from "../../types";

interface QuotationFormProps {
  quotation?: Quotation;
  onSave: (quotation: Quotation) => void;
  onCancel: () => void;
}

export function QuotationForm({ quotation, onSave, onCancel }: QuotationFormProps) {
  const [formData, setFormData] = useState<Partial<Quotation>>(
    quotation || {
      quotationNumber: "", // Will be generated by backend if empty, but we can show a placeholder
      date: new Date().toISOString().split("T")[0],
      validUntil: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split("T")[0],
      customerId: "",
      notes: "",
      terms: "Payment within 30 days",
      status: "Draft",
    }
  );

  const [items, setItems] = useState<Partial<QuotationItem>[]>(
    quotation?.items?.map(item => ({
      ...item,
      rate: Number(item.rate),
      taxRate: Number(item.taxRate),
      taxAmount: Number(item.taxAmount),
      amount: Number(item.total || item.amount),
    })) || []
  );

  // API hooks
  const { data: customersData, isLoading: isLoadingCustomers } = useCustomers();
  const { data: productsData, isLoading: isLoadingProducts } = useProducts();
  const createQuotationMutation = useCreateQuotation();
  const updateQuotationMutation = useUpdateQuotation();

  const customers = customersData?.data || [];
  const products = productsData?.data || [];

  const selectedCustomer = customers.find(c => c.id === formData.customerId);

  const addItem = () => {
    const newItem: Partial<QuotationItem> = {
      id: `new-${Date.now()}`,
      productId: "",
      productName: "",
      quantity: 1,
      unit: "",
      rate: 0,
      discount: 0,
      taxRate: 18,
      taxAmount: 0,
      amount: 0,
    };
    setItems([...items, newItem]);
  };

  const updateItem = (index: number, field: keyof QuotationItem, value: any) => {
    const updatedItems = [...items];
    const item = { ...updatedItems[index], [field]: value };

    // If product is selected, auto-fill details
    if (field === "productId" && value) {
      const product = products.find(p => p.id === value);
      if (product) {
        item.productName = product.name;
        item.rate = Number(product.sellingPrice || product.salePrice || 0);
        item.unit = product.unit;
        item.taxRate = Number(product.gstRate || 18);
      }
    }

    // Calculate totals for the item
    const quantity = Number(item.quantity) || 0;
    const rate = Number(item.rate) || 0;
    const discountPercent = Number(item.discount) || 0;
    const taxRate = Number(item.taxRate) || 0;

    const subtotal = quantity * rate;
    const discountAmount = (subtotal * discountPercent) / 100;
    const taxableAmount = subtotal - discountAmount;
    const taxAmount = (taxableAmount * taxRate) / 100;

    item.taxAmount = taxAmount;
    item.amount = taxableAmount + taxAmount;

    updatedItems[index] = item;
    setItems(updatedItems);
  };

  const removeItem = (index: number) => {
    setItems(items.filter((_, i) => i !== index));
  };

  const calculateTotals = () => {
    const subtotal = items.reduce((sum, item) => {
      const q = Number(item.quantity) || 0;
      const r = Number(item.rate) || 0;
      const d = Number(item.discount) || 0;
      return sum + (q * r * (1 - d / 100));
    }, 0);

    const totalTax = items.reduce((sum, item) => sum + (Number(item.taxAmount) || 0), 0);
    const totalAmount = subtotal + totalTax;

    return { subtotal, totalTax, totalAmount };
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.customerId || items.length === 0) {
      toast.error("Please select a customer and add at least one item");
      return;
    }

    const { subtotal, totalTax, totalAmount } = calculateTotals();

    const quotationData: any = {
      ...formData,
      items: items.map(item => ({
        productId: item.productId,
        productName: item.productName,
        quantity: Number(item.quantity),
        rate: Number(item.rate),
        taxRate: Number(item.taxRate),
        taxAmount: Number(item.taxAmount),
        total: Number(item.amount),
        discount: Number(item.discount || 0),
        unit: item.unit
      })),
      subtotal,
      totalTax,
      totalAmount,
    };

    try {
      if (quotation?.id) {
        await updateQuotationMutation.mutateAsync({ id: quotation.id, data: quotationData });
      } else {
        await createQuotationMutation.mutateAsync(quotationData);
      }
      onSave(quotationData);
    } catch (error) {
      // Error handled by mutation hook
    }
  };

  const totals = calculateTotals();

  // Columns definition for AdaptiveTable
  const itemColumns = [
    {
      header: "Product",
      className: "min-w-[200px]",
      cell: (item: any) => {
        const index = items.findIndex((i) => i.id === item.id);
        return (
          <select
            className="w-full flex h-10 rounded-md border border-input bg-background px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
            value={item.productId}
            onChange={(e) => updateItem(index, "productId", e.target.value)}
            required
          >
            <option value="">Select Product</option>
            {products.map((p) => (
              <option key={p.id} value={p.id}>{p.name}</option>
            ))}
          </select>
        );
      },
    },
    {
      header: "HSN",
      cell: (item: any) => (
        <Input
          value={products.find((p) => p.id === item.productId)?.hsnCode || "-"}
          readOnly
          placeholder="HSN"
          className="w-24 bg-muted"
        />
      ),
    },
    {
      header: "Qty",
      cell: (item: any) => {
        const index = items.findIndex((i) => i.id === item.id);
        return (
          <Input
            type="number"
            value={item.quantity}
            onChange={(e) => updateItem(index, "quantity", parseFloat(e.target.value))}
            min="1"
            className="w-20"
            required
          />
        );
      },
    },
    {
      header: "Unit",
      cell: (item: any) => {
        const index = items.findIndex((i) => i.id === item.id);
        return (
          <Input
            value={item.unit}
            onChange={(e) => updateItem(index, "unit", e.target.value)}
            placeholder="pcs"
            className="w-16"
          />
        );
      },
    },
    {
      header: "Rate",
      cell: (item: any) => {
        const index = items.findIndex((i) => i.id === item.id);
        return (
          <Input
            type="number"
            value={item.rate}
            onChange={(e) => updateItem(index, "rate", parseFloat(e.target.value))}
            min="0"
            step="0.01"
            className="w-24"
            required
          />
        );
      },
    },
    {
      header: "Disc%",
      cell: (item: any) => {
        const index = items.findIndex((i) => i.id === item.id);
        return (
          <Input
            type="number"
            value={item.discount}
            onChange={(e) => updateItem(index, "discount", parseFloat(e.target.value))}
            min="0"
            max="100"
            className="w-16"
          />
        );
      },
    },
    {
      header: "Tax%",
      cell: (item: any) => {
        const index = items.findIndex((i) => i.id === item.id);
        return (
          <Input
            type="number"
            value={item.taxRate}
            onChange={(e) => updateItem(index, "taxRate", parseFloat(e.target.value))}
            min="0"
            max="100"
            className="w-16"
          />
        );
      },
    },
    {
      header: "Amount",
      className: "text-right font-medium",
      cell: (item: any) => `₹${Number(item.amount).toFixed(2)}`,
    },
    {
      header: "Action",
      cell: (item: any) => {
        const index = items.findIndex((i) => i.id === item.id);
        return (
          <Button
            type="button"
            variant="ghost"
            size="sm"
            onClick={() => removeItem(index)}
          >
            <Trash2 className="size-4 text-destructive" />
          </Button>
        );
      },
    },
  ];

  const renderMobileItem = (item: any) => {
    const index = items.findIndex((i) => i.id === item.id);
    return (
      <div className="border border-border rounded-lg p-4 space-y-3">
        <div className="flex items-center justify-between">
          <p className="text-foreground">Item {index + 1}</p>
          <Button
            type="button"
            variant="ghost"
            size="sm"
            onClick={() => removeItem(index)}
          >
            <Trash2 className="size-4 text-destructive" />
          </Button>
        </div>
        <div className="space-y-3">
          <div>
            <Label>Select Product *</Label>
            <select
              className="w-full flex h-10 rounded-md border border-input bg-background px-3 py-2 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
              value={item.productId}
              onChange={(e) => updateItem(index, "productId", e.target.value)}
              required
            >
              <option value="">Select Product</option>
              {products.map((p) => (
                <option key={p.id} value={p.id}>{p.name}</option>
              ))}
            </select>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label>HSN Code</Label>
              <Input
                value={products.find((p) => p.id === item.productId)?.hsnCode || "-"}
                readOnly
                placeholder="HSN"
                className="bg-muted"
              />
            </div>
            <div>
              <Label>Unit</Label>
              <Input
                value={item.unit}
                onChange={(e) => updateItem(index, "unit", e.target.value)}
                placeholder="pcs"
              />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label>Quantity *</Label>
              <Input
                type="number"
                value={item.quantity}
                onChange={(e) => updateItem(index, "quantity", parseFloat(e.target.value))}
                min="1"
                required
              />
            </div>
            <div>
              <Label>Rate *</Label>
              <Input
                type="number"
                value={item.rate}
                onChange={(e) => updateItem(index, "rate", parseFloat(e.target.value))}
                min="0"
                step="0.01"
                required
              />
            </div>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <Label>Discount %</Label>
              <Input
                type="number"
                value={item.discount}
                onChange={(e) => updateItem(index, "discount", parseFloat(e.target.value))}
                min="0"
                max="100"
              />
            </div>
            <div>
              <Label>Tax %</Label>
              <Input
                type="number"
                value={item.taxRate}
                onChange={(e) => updateItem(index, "taxRate", parseFloat(e.target.value))}
                min="0"
                max="100"
              />
            </div>
          </div>
          <div className="pt-2 border-t border-border">
            <div className="flex justify-between font-medium">
              <p className="text-muted-foreground">Amount:</p>
              <p className="text-foreground">₹{Number(item.amount).toFixed(2)}</p>
            </div>
          </div>
        </div>
      </div>
    );
  };

  if (isLoadingCustomers || isLoadingProducts) {
    return (
      <div className="flex items-center justify-center h-64">
        <Loader2 className="size-8 animate-spin text-primary" />
      </div>
    );
  }

  return (
    <div className="space-y-4 md:space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Button variant="ghost" onClick={onCancel} size="sm">
          <ArrowLeft className="size-4" />
        </Button>
        <div>
          <h1 className="text-foreground">
            {quotation ? "Edit Quotation" : "New Quotation"}
          </h1>
          <p className="text-muted-foreground">
            Fill in the details below
          </p>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        {/* Basic Details Card */}
        <div className="card-base p-4 md:p-6 space-y-4">
          <h3 className="text-foreground">Basic Details</h3>
          <ResponsiveGrid columns="md:grid-cols-3">
            <div>
              <Label>Quotation Number *</Label>
              <Input
                value={formData.quotationNumber}
                onChange={(e) =>
                  setFormData({ ...formData, quotationNumber: e.target.value })
                }
                required
              />
            </div>
            <div>
              <Label>Date *</Label>
              <Input
                type="date"
                value={formData.date}
                onChange={(e) => setFormData({ ...formData, date: e.target.value })}
                required
              />
            </div>
            <div>
              <Label>Valid Until *</Label>
              <Input
                type="date"
                value={formData.validUntil}
                onChange={(e) =>
                  setFormData({ ...formData, validUntil: e.target.value })
                }
                required
              />
            </div>
          </ResponsiveGrid>
        </div>

        {/* Party Details Card */}
        <div className="card-base p-4 md:p-6 space-y-4">
          <h3 className="text-foreground">Party Details</h3>
          <ResponsiveGrid columns="md:grid-cols-2">
            <div>
              <Label>Select Customer *</Label>
              <select
                className="w-full flex h-10 rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
                value={formData.customerId}
                onChange={(e) => setFormData({ ...formData, customerId: e.target.value })}
                required
              >
                <option value="">Select a customer</option>
                {customers.map((c) => (
                  <option key={c.id} value={c.id}>{c.name}</option>
                ))}
              </select>
            </div>
            <div>
              <Label>GSTIN</Label>
              <Input
                value={selectedCustomer?.gstin || ""}
                readOnly
                placeholder="No GSTIN"
              />
            </div>
          </ResponsiveGrid>
          {selectedCustomer?.billingAddress && (
            <div>
              <Label>Address</Label>
              <Input
                value={`${selectedCustomer.billingAddress.address || ""}, ${selectedCustomer.billingAddress.city || ""}, ${selectedCustomer.billingAddress.state || ""}`}
                readOnly
              />
            </div>
          )}
        </div>

        {/* Items Section */}
        <div className="bg-white rounded-xl border border-border p-4 md:p-6 space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-foreground">Items</h3>
            <Button type="button" onClick={addItem} size="sm" className="bg-primary hover:bg-primary/90">
              <Plus className="size-4 mr-2" />
              Add Item
            </Button>
          </div>

          <AdaptiveTable
            data={items}
            columns={itemColumns}
            mobileRenderer={renderMobileItem}
          />

          {items.length === 0 && (
            <div className="text-center py-8 text-muted-foreground">
              No items added. Click "Add Item" to get started.
            </div>
          )}
        </div>

        {/* Terms & Notes */}
        <div className="bg-white rounded-xl border border-border p-4 md:p-6 space-y-4">
          <h3 className="text-foreground">Additional Information</h3>
          <div className="space-y-4">
            <div>
              <Label>Terms & Conditions</Label>
              <Textarea
                value={formData.terms}
                onChange={(e) => setFormData({ ...formData, terms: e.target.value })}
                placeholder="Enter terms and conditions"
                rows={3}
              />
            </div>
            <div>
              <Label>Notes</Label>
              <Textarea
                value={formData.notes}
                onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                placeholder="Any additional notes"
                rows={2}
              />
            </div>
          </div>
        </div>

        {/* Totals Summary */}
        <div className="card-base p-4 md:p-6">
          <div className="max-w-md ml-auto space-y-2">
            <div className="flex justify-between text-sm">
              <p className="text-muted-foreground">Subtotal:</p>
              <p className="text-foreground font-medium">₹{totals.subtotal.toFixed(2)}</p>
            </div>
            <div className="flex justify-between text-sm">
              <p className="text-muted-foreground">Total Tax:</p>
              <p className="text-foreground font-medium">₹{totals.totalTax.toFixed(2)}</p>
            </div>
            <div className="flex justify-between pt-2 border-t border-border text-lg font-bold">
              <p className="text-foreground">Total Amount:</p>
              <p className="text-primary">₹{totals.totalAmount.toFixed(2)}</p>
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex flex-col sm:flex-row gap-3 justify-end">
          <Button type="button" variant="outline" onClick={onCancel} className="sm:w-auto">
            Cancel
          </Button>
          <Button type="submit" className="bg-primary hover:bg-primary/90 sm:w-auto">
            <Save className="size-4 mr-2" />
            Save Quotation
          </Button>
        </div>
      </form >
    </div >
  );
}
